From: Sebastiaan van Stijn <github@gone.nl>
Date: Fri, 4 Jun 2021 16:32:37 +0200
Subject: vendor: github.com/containerd/containerd v1.5.2

full diff: https://github.com/containerd/containerd/compare/19ee068f93c91f7b9b2a858457f1af2cabc7bc06...v1.5.2

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
Origin: upstream, https://github.com/moby/moby/commit/7c1c1235
---
 plugin/backend_linux.go | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

Index: docker/engine/plugin/backend_linux.go
===================================================================
--- docker.orig/engine/plugin/backend_linux.go
+++ docker/engine/plugin/backend_linux.go
@@ -420,7 +420,7 @@ func (pm *Manager) Push(ctx context.Cont
 
 	// Make sure we can authenticate the request since the auth scope for plugin repos is different than a normal repo.
 	ctx = docker.WithScope(ctx, scope(ref, true))
-	if err := remotes.PushContent(ctx, pusher, desc, pm.blobStore, nil, func(h images.Handler) images.Handler {
+	if err := remotes.PushContent(ctx, pusher, desc, pm.blobStore, nil, nil, func(h images.Handler) images.Handler {
 		return images.Handlers(progressHandler, h)
 	}); err != nil {
 		// Try fallback to http.
@@ -432,7 +432,7 @@ func (pm *Manager) Push(ctx context.Cont
 			pusher, _ := resolver.Pusher(ctx, ref.String())
 			if pusher != nil {
 				logrus.WithField("ref", ref).Debug("Re-attmpting push with http-fallback")
-				err2 := remotes.PushContent(ctx, pusher, desc, pm.blobStore, nil, func(h images.Handler) images.Handler {
+				err2 := remotes.PushContent(ctx, pusher, desc, pm.blobStore, nil, nil, func(h images.Handler) images.Handler {
 					return images.Handlers(progressHandler, h)
 				})
 				if err2 == nil {
